site_name: EthStaker Knowledge Base
site_url: https://docs.ethstaker.org
theme:
  name: material
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      # primary: cyan
      # accent: cyan
    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      # primary: cyan
      # accent: cyan
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.code.copy
    - navigation.footer
exclude_docs: |
  exclude/*
  mkdocs.yml
  alphabetical-ordering.sh
  requirements.txt
  README.md
  tr/README.md
  ma/README.md
  fr/README.md
  es/README.md
  pt/README.md
plugins:
  - search
  - social
  - i18n:
      # https://ultrabug.github.io/mkdocs-static-i18n/fr/setup/setting-up-languages/
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: Español
          build: true
        - locale: fr
          name: Français
          build: true
        - locale: ms
          name: Malay
          build: true
        - locale: nl
          name: Dutch
          build: true
        - locale: pt
          name: Portuguese
          build: true
        - locale: tr
          name: Turkish
          build: true
repo_url: https://github.com/eth-educators/ethstaker-knowledgebase
repo_name: eth-educators/ethstaker-knowledgebase
edit_uri: edit/main/docs/
extra:
  analytics:
    provider: google
    property: G-XMMVX7SG3H
  site_url: https://docs.ethstaker.org
  social:
    - icon: fontawesome/brands/discord
      link: https://dsc.gg/ethstaker
    - icon: fontawesome/brands/github
      link: https://github.com/eth-educators
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/ethstaker
extra_css:
  - assets/css/style.css
extra_javascript:
  - assets/js/main.js
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
validation:
  nav:
    omitted_files: ignore
    absolute_links: ignore
  links:
    anchors: ignore
    absolute_links: ignore
    unrecognized_links: ignore
nav:
  - Introduction:
    - Table of contents: index.md
    - Glossary: staking-glossary.md
    - FAQ: faq.md
  - Getting Started:
    - What is Ethereum staking?: getting-started/what-is-ethereum-staking.md
    - Running a node without any ETH: getting-started/ethereum-node.md
    - Deposit process explained: getting-started/deposit-process.md
    - Withdrawal process explained:  getting-started/withdrawal-process-explained.md
  - Help!: 
    - My validator is offline! What do I do?: help/validator-offline.md
    - Missed attestations! What can I do?: help/missed-attestations.md
    - I'm worried about downtime!: help/downtime-explained.md
    - I'm worried about slashing 🔪: help/slashing-explained.md
    - Common errors and mistakes: help/common-errors-mistakes.md
  - Rewards: 
    - How does my validator earn ETH?: rewards/chain-rewards.md
    - Block proposal frequency: rewards/proposal-frequency.md
  - Hardware: 
    - Hardware requirements: hardware/hardware-requirements.md
    - Hardware examples: 
      - NUC - Eridian: hardware/hardware-examples/nuc-eridian.md
      - Custom Built Desktop - snoopmx: hardware/hardware-examples/custom-built-desktop.md
    - Hardware security: hardware/hardware-security.md
    - Hardware best practices: hardware/hardware-best-practices.md
  - Networking: 
    - Port forwarding: networking/port-forwarding.md
    - Firewalls and subnetting: networking/firewalls-and-subnetting.md
    - Brute-force SSH protection: networking/brute-force-ssh-protection.md
    - Setting up home VPN access: networking/setting-up-home-vpn-access.md
    - Setting up Tailscale VPN: networking/setting-up-tailscale-vpn.md
  - Validator Clients: 
    - Validator clients explained: validator-clients/validator-clients-explained.md
    - Execution clients: validator-clients/execution-clients.md
    - Consensus clients: validator-clients/consensus-clients.md
    - Checkpoint sync: validator-clients/checkpoint-sync.md
    - Validator effectiveness: validator-clients/validator-effectiveness.md
    - MEV boost: validator-clients/mev-boost.md
  - Validator Keys: 
    - Secure key generation: validator-keys/secure-key-generation.md
    - Slashing protection: validator-keys/slashing-protection.md
  - Tutorials: 
    - Solo staking guides: tutorials/solo-staking-guides.md
    - Installing Linux: tutorials/installing-linux.md
    - Use all available disk space: tutorials/confirm-available-disk-space.md
    - Automatic security updates: tutorials/automatic-security-updates.md
    - Connect with SSH: tutorials/connect-via-ssh.md
    - SSH security - 2FA: tutorials/ssh-security-2fa.md
    - Configuring an RPC endpoint: tutorials/rpc-endpoint.md
    - How to resync Geth: tutorials/resync-geth.md
    - Methods to minimize downtime: tutorials/methods-to-minimize-downtime.md
    - Safely migrating validator keys: tutorials/validator-key-migration.md
    - How to exit a validator: tutorials/how-to-exit-a-validator.md
    - Updating withdrawal credentials: tutorials/updating-withdrawal-credentials.md
  - DVT: 
    - Obol DVT: dvt/obol-dvt.md
    - SSV DVT: dvt/ssv-dvt.md
  - Scaled Node Operators:
    - What is a scaled node operator?: scaled-node-operators/what-is-a-scaled-node-operator.md
    - Security at scale: scaled-node-operators/security-at-scale.md
    - Node health checks: scaled-node-operators/node-health-checks.md
    - On-Call/Incidence response: scaled-node-operators/on-call-incidence-response.md
    - Alerting at scale: scaled-node-operators/alerting-at-scale.md
    - MEV at scale: scaled-node-operators/mev-at-scale.md
    - Updates at scale: scaled-node-operators/updates-at-scale.md
    - Resource scaling: scaled-node-operators/resource-scaling.md
    - Key management at scale: scaled-node-operators/key-management-at-scale.md
    - Migration at scale: scaled-node-operators/migration-at-scale.md
    - Monitoring at scale: scaled-node-operators/monitoring-at-scale.md
    - Uptime at scale: scaled-node-operators/uptime-at-scale.md
  - Get Involved: 
    - Content ideas: get-involved/content-ideas.md
    - Code of conduct: get-involved/code-of-conduct.md
    - How to contribute: get-involved/how-to-contribute.md
    - Privacy policy: privacy-policy.md
  - Guides:
    - Router:
      - Overview: guides/router/overview.md
      - Prepare: guides/router/prepare.md
      - Netgear Router Setup:
        - Initial Setup: guides/router/netgear/rs300-initial-setup.md
        - Port Forwarding: guides/router/netgear/rs300-port-forwarding.md
      - Final Switchover:
        - Comcast: guides/router/final-switchover/comcast-bridge.md
    - Holesky Testnet:
      - Lighthouse/Nethermind: guides/holesky-testnet/holesky-nethermind-lighthouse.md
      - Lodestar/Reth: guides/holesky-testnet/holesky-reth-lodestar.md
    - Monitoring and Maintenance:
      - Monitoring: guides/monitoring-maintenance/monitoring.md
      - Alerting: guides/monitoring-maintenance/alerting.md
      - Maintenance and Security: guides/monitoring-maintenance/security-maintenance.md
      - Migrate to a larger disk: guides/monitoring-maintenance/migrating-to-a-larger-disk.md
    - MEV relay list: guides/MEV-relay-list.md









